# Generated by Django 4.2.7 on 2025-07-29 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('dancer', 'Dancer'), ('acrobat', 'Acrobat'), ('performer', 'Performer'), ('musician', 'Musician'), ('entertainer', 'Entertainer'), ('bar_service', 'Bar & Service Talent')], max_length=20)),
                ('bio', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('gender_identification', models.CharField(blank=True, max_length=50)),
                ('pronouns', models.CharField(blank=True, max_length=20)),
                ('hair_color', models.CharField(blank=True, max_length=30)),
                ('eye_color', models.CharField(blank=True, max_length=30)),
                ('agency', models.CharField(blank=True, max_length=100)),
                ('union_affiliations', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='talent_videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='talents.talentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TalentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='talents.talentprofile')),
            ],
        ),
    ]
