# Generated by Django 4.2.7 on 2025-07-29 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='talentvideo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='talentphoto',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='email_private',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='is_publicly_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='last_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='public_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talentvideo',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', max_length=10),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='role',
            field=models.CharField(choices=[('dancer', 'Dancer'), ('acrobat', 'Acrobat'), ('performer', 'Performer'), ('musician', 'Musician'), ('entertainer', 'Entertainer'), ('bar_service', 'Bar & Service Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='talentvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL only', null=True),
        ),
        migrations.CreateModel(
            name='ProfileUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('changes_summary', models.TextField()),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='talents.talentprofile')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
