# Generated by Django 4.2.7 on 2025-07-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_remove_talentprofile_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='last_approved_version',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
